// config.h - Generated by EX-Installer v0.0.20 for EX-CommandStation v5.4.20-Prod

#define IP_PORT 2560
#define SCROLLMODE 1
#define MOTOR_SHIELD_TYPE EXCSB1
#define OLED_DRIVER 132,64
#define WIFI_HOSTNAME "dccex"
#define WIFI_SSID "Your network name"
#define WIFI_PASSWORD "Your network passwd"
#define ENABLE_WIFI true
#define WIFI_CHANNEL 1
#define DISABLE_EEPROM



